### ISSUE TITLE
Missing function `sdrad_get_stack_offset` when linking

### ISSUE THREAD

**Issue by jialunzhang-psu** [EricssonResearch/sdradrustffi#1]
When compiling the following code

```rust
#![feature(allocator_api)]
use sdradrustffi::*;
use std::os::raw::c_void;
sandbox!(
    fn f(a: &[i32]) {}
);

fn main() {
    f(&[3]);
}
```

The linker complains about it referring a missing function as follows
```
sdradrustffi/src/lib.rs:89: undefined reference to `sdrad_get_stack_offset'
```

But this function doesn't exist in the `sdrad` library. Where can I find it?

**Comment by gulmezmerve** [comment]
"Thank you for reaching out!

The sdrad library includes a branch named 'sdrad_ffi', which features an expanded API to support sdradrustffi. 

Although sdradrustffi incorporates secure-rewind-and-discard as a submodule via the sdrad_ffi branch, when sdradrustffi is called from another crate, it ignores the sdrad_ffi branch for the sdrad library. I am currently exploring how I can solve it. 

For now, the manual solution involves cloning sdradrustffi to your local machine and specifying the path to sdradrustffi in your Cargo.toml file.

Sorry for the inconvenience!

**Comment by gulmezmerve** [comment]
@jialunzhang-psu  I fixed the problem with this commit. https://github.com/EricssonResearch/sdradrustffi/commit/dc8cbbf60169bcff3a2ff2fea24aa05fc9ff1b81

Also I tested your code here. https://github.com/secure-rewind-and-discard/secure-rewind-and-discard-rust-ffi/tree/main/issue1 

Please let me know if you have problems!

**Comment by jialunzhang-psu** [comment]
It works fine now!
